package com.omsworld.familycare.core

/**
 * All API endpoints. Replaces UrlList.java.
 */
object UrlList {

    @JvmField var domainURL: String = "http://familycares.in/family-care/Api"

    // ========== Legacy PHP endpoints ==========
    @JvmField var reg_with_mob = "$domainURL/reg_with_mob.php"
    @JvmField var LOG_IN = "$domainURL/log.php"
    @JvmField var registration_step1 = "$domainURL/registration_step1.php"
    @JvmField var registration_step2 = "$domainURL/registration_step2.php"
    @JvmField var verify_otp = "$domainURL/verify_otp.php"
    @JvmField var forgot_pass = "$domainURL/forgot_pass.php"
    @JvmField var push_registration = "$domainURL/push_registration.php"
    @JvmField var Country_Code = "http://webapihoc.co.in/api/v1/Group/CountryCode"
    @JvmField var resend_otp = "$domainURL/resend_otp.php"
    @JvmField var family_group_info = "$domainURL/family_group_info.php"
    @JvmField var request_to_join = "$domainURL/request_to_join.php"
    @JvmField var add_family_on_group = "$domainURL/add_family_on_group.php"
    @JvmField var family_request_action = "$domainURL/family_request_action.php"
    @JvmField var insert_position = "$domainURL/insert_position.php"
    @JvmField var change_pass = "$domainURL/change_pass.php"
    @JvmField var profile_edit = "$domainURL/profile_edit.php"
    @JvmField var upload_image = "$domainURL/upload_image.php"
    @JvmField var ResendOtp = "$domainURL/resend_otp.php"
    @JvmField var phone_book_list = "$domainURL/phone_book_list.php"
    @JvmField var edit_phone_book = "$domainURL/edit_phone_book.php"
    @JvmField var add_phone_book = "$domainURL/add_phone_book.php"
    @JvmField var delete_phone_book = "$domainURL/delete_phone_book.php"
    @JvmField var term_condition = "http://108.170.54.215/App_development/Tracking/privacy/termofuse.html"
    @JvmField var user_chat_list = "$domainURL/user_chat_list.php"
    @JvmField var user_chat_details = "$domainURL/user_chat_details.php"
    @JvmField var show_diary = "$domainURL/show_diary.php"
    @JvmField var add_diary = "$domainURL/add_diary.php"
    @JvmField var user_chat = "$domainURL/demo_user_chat.php"
    @JvmField var edit_diary = "$domainURL/edit_diary.php"
    @JvmField var delete_diary = "$domainURL/delete_diary.php"
    @JvmField var user_suggestion = "$domainURL/user_suggestion.php"
    @JvmField var groceries_list = "$domainURL/groceries_list.php"
    @JvmField var add_groceries_list = "$domainURL/add_groceries_list.php"
    @JvmField var add_shopped_groceries = "$domainURL/add_shopped_groceries.php"
    @JvmField var direct_purchase = "$domainURL/direct_purchase.php"
    @JvmField var shopped_groceries_history = "$domainURL/shopped_groceries_history.php"
    @JvmField var news_list = "$domainURL/news_list.php"
    @JvmField var delete_groceries_item = "$domainURL/delete_groceries_item.php"
    @JvmField var like_news = "$domainURL/like_news.php"
    @JvmField var unlike_news = "$domainURL/unlike_news.php"
    @JvmField var create_family_group = "$domainURL/create_family_group.php"
    @JvmField var remove_family_group_member = "$domainURL/remove_family_group_member.php"
    @JvmField var leave_family_group = "$domainURL/leave_family_group.php"
    @JvmField var shopping_site_list = "$domainURL/shopping_site_list.php"
    @JvmField var shopping_category = "$domainURL/shopping_category.php"

    // ========== v1 REST endpoints ==========
    @JvmField var Package = "$domainURL/v1/User/Package"
    @JvmField var promocode = "$domainURL/v1/User/promocode"
    @JvmField var UserInfo = "$domainURL/v1/User/UserInfo"
    @JvmField var ResendMail = "$domainURL/v1/User/ResendMail"
    @JvmField var UPDATE_APK = "$domainURL/v1/Notification/GetAppVersion"
    @JvmField var DELETEUSER = "$domainURL/v1/Family/DeleteUser"
    @JvmField var CountryCode = "http://webapihoc.co.in/api/v1/Group/CountryCode"
    @JvmField var DeleteAccount = "$domainURL/v1/Group/DeletedMyAccount"
    @JvmField var GetProfile = "$domainURL/v1/Group/GetProfile"
    @JvmField var RESENDINVITATION = "$domainURL/v1/Family/ReSendInvitation"
    @JvmField var UPDATEPAYMENT = "$domainURL/v1/User/UpdatePayment"
    @JvmField var ALARMONOFFREQUEST = "$domainURL/v1/Notification/AlarmOnOffRequest"
    @JvmField var ProcessPayment = "$domainURL/v1//Payment/ProcessPayment"
    @JvmField var ValidateReferralCode = "$domainURL/v1/Payment/ValidateReferralCode"
    @JvmField var whoIsTrackingMe = "$domainURL/v1/Group/whoIsTrackingMe"
}